[package]
name = "godlint-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "Command-line interface for Godlint."
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
godlint-core = { path = "../godlint-core", version = "0.1.5" }

[dev-dependencies]
serde.workspace = true
yaml_serde.workspace = true

[lints]
workspace = true

[[bin]]
name = "godlint"
path = "src/main.rs"
