name: Lint

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Run Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: rustup toolchain install 1.97.1 --profile minimal

      - run: rustup component add clippy --toolchain 1.97.1

      - run: cargo +1.97.1 clippy --workspace --all-targets -- -D warnings
